# -*- coding: utf-8 -*-
"""boston-housing-price-dl-assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oh4KcUrQ-nuqAOIQAz6Pfklf8VX7xwXk
"""

import numpy as np
import pandas as pd
import tensorflow as tf

# Load the Boston housing dataset
boston_data = pd.read_csv('/content/Boston.csv')

boston_data.head()

# Perform exploratory data analysis
boston_data.describe()
boston_data.hist()

# Identify the features and target variable
features = ['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'black', 'lstat']
target = 'medv'

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(boston_data[features], boston_data[target], test_size=0.2)

# Create a neural network model with one hidden layer
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(12, activation='relu'),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(X_train, y_train, epochs=200)

# Evaluate the model on the testing set
model.evaluate(X_test, y_test)

# Make predictions on new data
predictions = model.predict(X_test)

# Calculate MSE and RMSE
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)
print('MSE:', mse)
print('RMSE:', rmse)
print('MAE:', mae)
print('R2 Score:', r2)

for i in range(10):
    print('Prediction:', predictions[i][0], 'Actual:', y_test.iloc[i])



